Hotfix/document loader
matipojo/elementor pull request #18
Opened 2020-01-09 17:46 UTC by iNewLegend

2020-01-09 17:50 UTC, iNewLegend commented on assets/dev/js/editor/commands/open.js
> +
Remove

2020-01-09 17:51 UTC, iNewLegend reviewed
Change

2020-01-12 12:41 UTC, matipojo requested changes

2020-01-12 12:41 UTC, matipojo commented on assets/dev/js/editor/document/save/component.js
> -		this.autoSaveTimer = null;
BC

2020-01-12 12:41 UTC, matipojo commented on assets/dev/js/editor/document/save/component.js
> -	startTimer( hasChanges ) {
BC

2020-01-12 12:41 UTC, matipojo commented on assets/dev/js/editor/editor-base.js
> -		this.saver = $e.components.get( 'document/save' );
BC

2020-01-12 12:41 UTC, matipojo commented on core/common/assets/js/api/modules/component-base.js
> +	onInit() {}
Already exist? see `elementorModules.Module`

2020-01-12 12:41 UTC, matipojo commented on tests/qunit/core/common/assets/js/api/core/components.spec.js
> +				getNamespace() {
Why?

2020-01-12 12:41 UTC, matipojo commented on tests/qunit/core/common/assets/js/api/core/components.spec.js
> +				defaultTabs() {
Why?

2020-01-12 12:41 UTC, matipojo commented on assets/dev/js/editor/editor-document.js
> +	elementor.saver = $e.components.get( 'document/save' );
`defineProperty` as deprecated.

2020-01-12 13:58 UTC, merged