Draft/commands component
matipojo/elementor pull request #8
Opened 2019-05-16 14:13 UTC by matipojo

2019-05-20 14:59 UTC, kobizz requested changes

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/modules/imports/component.js
> +		if ( undefined !== typeof position ) {
You can just write `if ( position )`

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/editor/components/hotkeys/component.js
> +		this.title = 'Shortcuts';
Is it not supposed to be translated?

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/editor/components/hotkeys/component.js
> +		};
What is?

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/editor/components/hotkeys/component.js
> +		return true;
Why is the returning value required?

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/editor/components/hotkeys/hotkeys.js
> +		elementorCommon.components.register( new Component(), { parent: this } );
I'm not sure if `parent` is the right term

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/editor/components/settings/general/component.js
> +		this.title = 'Global Settings';
Same as above

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/editor/editor.js
> +			element: '.elementor-panel-footer-tool.elementor-toggle-state',
What is?

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/editor/elements/component.js
> +// TODO: Maybe it should merge with panel/elements?
What is this component responsible for?

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/editor/regions/navigator/component.js
> +		return {
?

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/editor/regions/panel/pages/elements/component.js
> +export default class extends elementorModules.Component {
I'm not sure all of these components are really necessary

2019-05-20 14:59 UTC, kobizz commented on assets/dev/js/modules/imports/component.js
> +		if ( this.tabRenderer ) {
Needs more clarification

2019-05-20 14:59 UTC, kobizz commented on core/common/assets/js/utils/shortcuts.js
> +				const InScope = handler.scope.some( ( scope ) => {
`inScope`

2019-05-20 14:59 UTC, kobizz commented on core/common/modules/finder/assets/js/component.js
> +		return {
?

2019-05-20 14:59 UTC, kobizz commented on includes/editor-templates/panel-elements.php
>  	<div id="elementor-panel-elements-navigation" class="elementor-panel-navigation">
Why?

2019-05-20 17:30 UTC, matipojo commented on assets/dev/js/modules/imports/component.js
> +		if ( undefined !== typeof position ) {
It can be 0.

2019-05-22 10:47 UTC, kobizz commented on core/common/assets/js/utils/components.js
> +		component.init( args );
Use `__construct`

2019-05-22 10:47 UTC, kobizz commented on assets/dev/js/editor/components/hotkeys/hotkeys.js
> +		elementorCommon.components.register( new Component(), { parent: this } );
context

2019-05-22 10:57 UTC, kobizz commented on assets/dev/js/editor/editor.js
> +			element: '.elementor-panel-footer-tool.elementor-toggle-state',
Remove CSS

2019-05-22 11:22 UTC, kobizz requested changes

2019-05-22 11:22 UTC, kobizz commented on modules/history/assets/js/module.js
> +			tabRenderer: ( tab ) => elementor.getPanelView().setPage( 'historyPage' ).showView( tab ),
`renderTab`

2019-05-26 13:29 UTC, matipojo commented on assets/dev/js/editor/editor.js
> +			element: '.elementor-panel-footer-tool.elementor-toggle-state',
Nothing to remove

2019-11-04 15:38 UTC, closed without merging